### ISSUE TITLE
how does a cookie protect against CSRF?

### ISSUE THREAD

**Issue by wmertens** [Tarang11/fastify-csrf#10]
If the CSRF token is in a cookie, that means all the data needed to make a request is known to the attacker (just the API call), and the browser adds the session and csrf secrets.

So isn't putting the CSRF token in a cookie pointless?

**Comment by Tarang11** [comment]
It depends how you use it. If you don't want to store session on your backend you can use cookie to store token secret in cookie. If cookie itself is compromised, there is no use in using csrf. So as a user you have to decide which option is better for you. For more info see expressjs/csrf

**Comment by wmertens** [comment]
Ah yes, it wasn't clear to me that the cookie is only to avoid session storage. Thanks!
