### ISSUE TITLE
TypeScript definitions file is not published to the npm registry

### ISSUE THREAD

**Issue by jurca** [Tarang11/fastify-csrf#12]
Hello,

it appears that the [fastifyCsrf.d.ts](https://github.com/Tarang11/fastify-csrf/blob/master/lib/fastifyCsrf.d.ts) file is not present in the published npm package in the [npm registry](https://www.npmjs.com/package/fastify-csrf).

Could you please re-publish this package with the definitions included?

Thanks a lot!

**Comment by Tarang11** [comment]
Having issue with npm account. Will publish package in day or two.
