### ISSUE TITLE
Typescript definitions not working

### ISSUE THREAD

**Issue by mksony** [Tarang11/fastify-csrf#15]
Hi there,
I tried to use this module with the provided typescript definitions and got 

```
Argument of type '<HttpServer = any, HttpRequest = any, HttpResponse = any>(opts?: Options<HttpRequest> | undefined) => Plugin<HttpServer, HttpRequest, HttpResponse>' is not assignable to parameter of type '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse>, options: { cookie: boolean; }, callback: (err?: FastifyError | undefined) => void) => void'.
  Types of parameters 'opts' and 'instance' are incompatible.
```

when using it via

```ts
server.register(fastifyCsrf, {cookie: true});
```

what actually worked for me are the following typings:

```ts
import {IncomingMessage, Server, ServerResponse} from "http";
import * as fastify from "fastify";
import {Options as TokenOptions} from "csrf";

declare module "fastify" {
    interface FastifyRequest {
        csrfToken(): string;
    }
}

interface Options<HttpRequest> extends TokenOptions {
    value?: (req: HttpRequest) => string;
    cookie?: fastify.CookieSerializeOptions | boolean;
    ignoreMethods?: Array<string>;
    sessionKey?: string;
}

declare const fastifyCsrf: fastify.Plugin<
    Server,
    IncomingMessage,
    ServerResponse,
    Options<ServerResponse>
>;

export = fastifyCsrf;
```

Would you accept a PR for this change? Or is there another way to make it work?

**Comment by baremaximum** [comment]
I had the same issue. This would be helpful.

**Comment by Tarang11** [comment]
@jurca, can you have a look at this.

**Comment by jurca** [comment]
@Tarang11 I confirm that the TypeScript definitions are out of date. While I was aware of this issue, I did not have time to fix them back then unfortunately :-( , but I do now.

I see two options: either update the TypeScript definitions (less work), or port the project to TypeScript (better maintainability). I'm willing to do the work and submit a PR.

Which option would you prefer?

**Comment by Tarang11** [comment]
@jurca, just update the Typescript definitions. This keeps it simple for us and for the users as well.

**Comment by jurca** [comment]
@Tarang11 Very well, but I think credit should go where credit is due, if you agree.

@mksony Would you submit a PR for this, please?

@Tarang11  I'll do the PR review :).

**Comment by Tarang11** [comment]
ok

**Comment by mksony** [comment]
@jurca I submitted a PR #17 and also included a test for the typings. Let me know what you think 🙂

**Comment by jurca** [comment]
@Tarang11 Would you please publish a new version to npm?
