### ISSUE TITLE
Fasify 3 warning

### ISSUE THREAD

**Issue by bardak-dev** [Tarang11/fastify-csrf#18]
https://github.com/Tarang11/fastify-csrf/blob/cd91f80a4d1a4cfd1226b97a4f3923b7b14a1e26/lib/fastifyCsrf.js#L35

(node:4186) [FSTDEP001] FastifyDeprecation [FSTDEP001]: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.

**Comment by wesselvdv** [comment]
The type definitions are also out of date.
